[build]
  publish = "."
  command = "echo 'Static site ready'"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/exam"
  to = "/exam.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200